### ISSUE TITLE
Locale prop not working after update to version 1.0.4

### ISSUE THREAD

**Issue by haeniya** [FaridSafi/react-native-gifted-chat#2293]
#### Issue Description

After an update to the version 1.0.4 from 0.16.3 the `locale` prop of the GiftedChat component doesn't seem to work anymore.
Only the English format (en) is displayed regardless of what is passed as locale.

#### Steps to Reproduce / Code Snippets

```js
import 'dayjs/locale/de';
...
<GiftedChat
    ref={chatRef}
    infiniteScroll
    loadEarlier
    onLoadEarlier={() => loadEarlierMessages()}
    messages={messages}
    renderBubble={renderBubble}
    renderTime={renderTime}
    renderDay={renderDay}
    renderComposer={renderComposer}
    renderSend={renderSend}
    locale="de"
    renderLoadEarlier={() => null}
    onSend={(m) => onSend(m)}
    user={{
      _id: sessionStore.authUser?.id || ''
    }}
    bottomOffset={insets.bottom}
  />
```
The above code works in version 0.16.3 and displays times and dates in German format. In version 1.0.4, the English format is shown.

#### Expected Results

Passed `locale` should be used correctly.

#### Additional Information

* Nodejs version: 16.16.0
* React version: 17.0.7
* React Native version: 0.68.2
* expo: 45.0.0
* react-native-gifted-chat version: 1.0.4
* Platform(s): Both iOS and Android
* TypeScript version: 4.3.5
* dayjs: 1.11.5

**Comment by quape** [comment]
Same here. However, when I do `import de from 'dayjs/locale/de'` and then `locale={de}` (which makes no sense) a warning is shown that `locale` must be of type string (of course) - BUT: the date format is now displayed in German. Have no idea why!

I now temporarily solved this issue by creating my own Day and Time components and passing them to the Chat using `renderDay` and `renderTime`.

**Comment by haeniya** [comment]
Over a month old now. Anything else I can provide or do to get this fixed?

**Comment by levepic** [comment]
Same here!

**Comment by c-goettert** [comment]
I also had to pass the day-js imported locale as locale prop in previous versions, but for me it seems to be fixed with `1.1.0`. @haeniya's example is now working for me, without any prop-type issues 🥳

**Comment by haeniya** [comment]
Thanks for the hint @c-goettert. I tried updating to 1.1.0 but the issue still exists for me. I also don't see any changes in the changelog that would fix this. @levepic did updating solve the issue on your end?

**Comment by levepic** [comment]
Yes updating fixed it for me too! (might try to remove & install instead of update)

**Comment by fgnass** [comment]
In my case, the issue was the following:

There were two versions of dayjs, one in `node_modules/dayjs` and one in `node_modules/react-native-gifted-chat/node_modules/dayjs` that did not get deduped because gifted-chat depends on this exact version: `dayjs@1.8.26`. I fixed the issue by specifying the exact same version in my package.json and doing a fresh `npm install`.

**Comment by haeniya** [comment]
Thanks a lot for sharing @fgnass! This seems to solve the issue for me too!

**Comment by strivelen** [comment]
Similarly, I encountered that dynamically updating the value of locale does not work, but I solved this problem, when I switch languages, I will call `giftedChatRef.current.setLocale("en")`, which will switch to what I want look. Hope to help everyone.

#### Verison Info
* react-native-gifted-chat version: "2.0.1"

**Comment by levepic** [comment]
> Thanks for the hint @c-goettert. I tried updating to 1.1.0 but the issue still exists for me. I also don't see any changes in the changelog that would fix this. @levepic did updating solve the issue on your end?

The problem is back Im not sure why but its happening again. Now on 2.0 when I do the hack described here, some users receive a 
`TypeError: Cannot read property 'replace' of undefined

This error is located at:
    in Day
    in RCTView
    in Unknown
    in Message`
