### ISSUE TITLE
Unusal height in EXPO RN!!!!

### ISSUE THREAD

**Issue by prashantkumar23** [FaridSafi/react-native-gifted-chat#2425]
#### Issue Description

By opening keyboard for the first time am getting the unusal height below the textinput

#### Steps to Reproduce / Code Snippets

```
 <SafeAreaProvider>
        <GiftedChat
          messages={messages}
          //@ts-ignore
          onSend={(messages) => onSend(messages)}
          user={{
            _id: 1,
          }}
          bottomOffset={insets.bottom}
        />
      <KeyboardAvoidingView behavior={"padding"} style={{backgroundColor: "green",}}/>
    </SafeAreaProvider>
```

Video Link: [Bug Video](https://youtube.com/shorts/35-ZNxIHjLE?feature=share)

* Nodejs version: [18.15.0]
* React version: [18.2]
* React Native version: [0.17.8]
* react-native-gifted-chat version: [2.40.0]
* Platform(s) (iOS, Android, or both?): [Android]
* TypeScript version: [5.0.4]

**Comment by NiharR27** [comment]
Just curious, why do you even need KeyboardAvoidingView?

I have something like
```
import {  SafeAreaView } from 'react-native';

 <SafeAreaView style={{ flex: 1 }}>
        <GiftedChat />
</SafeAreaView>

```

and that seem to be working as expected..

Also, if you look here: https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.tsx

the package does seem to do the calculations...

**Comment by NiharR27** [comment]
Also take a look at https://github.com/FaridSafi/react-native-gifted-chat/issues/2409. did you try giving bottomOffset?

**Comment by quannguyen291** [comment]
Hi @NiharR27, I'm facing the same issue. The GiftChat is inside a Bottom Tab. I see that `bottomOffset` props is removed on the the latest version `2.6.0`. Do you have any idea? Thank you so much
![simulator_screenshot_14665FD1-65A7-443B-98DC-8298CB342D65](https://github.com/user-attachments/assets/4b88cdfa-4fb4-450a-be4b-1011774a59d5)

```
   <SafeAreaView style={layout.flex_1}>
      <GiftedChat
        {...{ messages, onSend }}
        user={{
          _id: 1,
        }}
        alwaysShowSend
        // alignTop
        // bottomOffset={50}
        renderBubble={renderBubble}
        renderDay={renderDay}
        renderTime={() => <View />}
        listViewProps={{
          ListFooterComponent: (
            <View style={styles.userInfoContainer}>
              <Text style={styles.userName}>John Doe</Text>
              <Text style={styles.userStatus}>Online</Text>
            </View>
          ),
          contentContainerStyle: {
            flexGrow: 1,
            justifyContent: 'flex-end',
          },
        }}
      />
    </SafeAreaView>
```

**Comment by NiharR27** [comment]
@quannguyen291 - haven't really tried the latest version, but i will soon at let you know if i face this / how i fixed it in-case i do

**Comment by anhquan291** [comment]
Hi @NiharR27 , It works after add the `isKeyboardInternallyHandled={false}` and wrap the GiftChat inside the `KeyboardAvodingView`. Thank you
```
     <KeyboardAvoidingView
        behavior="padding"
        style={[layout.flex_1, { backgroundColor: colors.background }]}
      >
        <GiftedChat
          {...{ messages, onSend }}
          user={{
            _id: 1,
          }}
          alwaysShowSend
          isKeyboardInternallyHandled={false}
          // alignTop
          renderBubble={renderBubble}
          renderDay={renderDay}
          renderTime={() => <View />}
          listViewProps={{
            ListFooterComponent: (
              <View style={styles.userInfoContainer}>
                <Text style={styles.userName}>John Doe</Text>
                <Text style={styles.userStatus}>Online</Text>
              </View>
            ),
            contentContainerStyle: {
              flexGrow: 1,
              justifyContent: 'flex-end',
            },
          }}
        />
      </KeyboardAvoidingView>
```

**Comment by NiharR27** [comment]
> Hi @NiharR27 , It works after add the `isKeyboardInternallyHandled={false}` and wrap the GiftChat inside the `KeyboardAvodingView`. Thank you
> 
> ```
>      <KeyboardAvoidingView
>         behavior="padding"
>         style={[layout.flex_1, { backgroundColor: colors.background }]}
>       >
>         <GiftedChat
>           {...{ messages, onSend }}
>           user={{
>             _id: 1,
>           }}
>           alwaysShowSend
>           isKeyboardInternallyHandled={false}
>           // alignTop
>           renderBubble={renderBubble}
>           renderDay={renderDay}
>           renderTime={() => <View />}
>           listViewProps={{
>             ListFooterComponent: (
>               <View style={styles.userInfoContainer}>
>                 <Text style={styles.userName}>John Doe</Text>
>                 <Text style={styles.userStatus}>Online</Text>
>               </View>
>             ),
>             contentContainerStyle: {
>               flexGrow: 1,
>               justifyContent: 'flex-end',
>             },
>           }}
>         />
>       </KeyboardAvoidingView>
> ```

Perfect, thanks mate! I will keep that in mind when I bump up the package on my projects. Have a nice weekend

**Comment by vinhnglx** [comment]
The `isKeyboardInternallyHandled` has been removed in the latest version - I have to roll back to 2.4.0 at this moment

**Comment by jordo-harmonic** [comment]
I'm still seeing this on 2.6.5 and i've tried using the KeyboardAvoidingView, bottomOffset(https://github.com/FaridSafi/react-native-gifted-chat/issues/2409#issuecomment-1614028174) and even setting maxComposerHeight(https://github.com/FaridSafi/react-native-gifted-chat/issues/2409#issuecomment-2475702498)

This is on a greenfield / newly generated app, so i have very few customizations. I'm also basing it off of the example app in the demo section (https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.tsx).

Nothing works. any thoughts?

**Comment by kesha-antonov** [comment]
Please check examples. They're working now
